# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('personid', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('work_place', models.CharField(max_length=250)),
                ('work_time', models.CharField(choices=[('1', '1 a\xf1o'), ('2', '2 a\xf1os'), ('3', '3 a\xf1os'), ('4', '4 a\xf1os'), ('5', '5 a\xf1os'), ('6', '6 a\xf1os'), ('7', '7 a\xf1os'), ('8', '8 a\xf1os'), ('9', '9 a\xf1os')], max_length=1)),
                ('income_range', models.CharField(choices=[('1', 'RD$8,000 - 15,000'), ('2', 'RD$15,000 - 25,000'), ('3', 'RD$25,000 - 35,000'), ('4', 'RD$35,000 - 45,000'), ('5', 'RD$45,000 - 55,000'), ('6', 'RD$55,000 - 65,000'), ('7', 'RD$65,000 - 75,000'), ('8', 'RD$75,000 - 85,000'), ('9', 'RD$85,000 - 95,000'), ('10', 'RD$95,000 - 100,000'), ('11', 'RD$95,000 - 100,000'), ('12', 'RD$100,000 - 110,000'), ('13', 'RD$110,000 - +')], max_length=2)),
                ('loan_reason', models.CharField(choices=[('1', 'Prestamo personal'), ('2', 'Compra vehiculo'), ('3', 'Compra casa')], max_length=1)),
                ('loan_amount', models.IntegerField()),
                ('loan_time', models.IntegerField()),
                ('pictures', models.ImageField(upload_to=b'')),
                ('date_req', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_phone', models.CharField(max_length=15)),
                ('p_message', models.CharField(max_length=500)),
            ],
        ),
    ]
