# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20171101_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='pictures',
        ),
    ]
