# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='p_message',
            field=models.TextField(max_length=500),
        ),
    ]
