# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20171101_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='p_message',
            field=models.TextField(max_length=2000),
        ),
    ]
