# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20171101_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='address',
            field=models.CharField(default='DR', max_length=400),
        ),
        migrations.AddField(
            model_name='loan',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 15, 17, 48, 54, 803000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='loan',
            name='civil_status',
            field=models.CharField(choices=[('0', 'Soltero/a'), ('1', 'Casado/a')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='loan',
            name='other_income',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='phone_home',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='phone_office',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='province',
            field=models.CharField(choices=[('Santo Domingo Este', 'Santo Domingo Este'), ('Distrito Nacional', 'Distrito Nacional'), ('Santiago', 'Santiago'), ('San Crist\xf3bal', 'San Crist\xf3bal'), ('La Vega', 'La Vega'), ('Puerto Plata', 'Puerto Plata'), ('San Pedro de Macor\xeds', 'San Pedro de Macor\xeds'), ('Duarte', 'Duarte'), ('La Altagracia', 'La Altagracia'), ('La Romana', 'La Romana'), ('San Juan', 'San Juan'), ('Espaillat', 'Espaillat'), ('Azua', 'Azua'), ('Barahona', 'Barahona'), ('Monte Plata', 'Monte Plata'), ('Peravia', 'Peravia'), ('Monsenor Nouel', 'Monse\xf1or Nouel'), ('Valverde', 'Valverde'), ('Sanchez Ramirez', 'S\xe1nchez Ram\xedrez'), ('Maria Trinidad Sanchez', 'Mar\xeda Trinidad S\xe1nchez'), ('Montecristi', 'Montecristi'), ('Samana', 'Saman\xe1'), ('Bahoruco', 'Bahoruco'), ('Hermanas Mirabal', 'Hermanas Mirabal'), ('El Seibo', 'El Seibo'), ('Hato Mayor', 'Hato Mayor'), ('Dajabon', 'Dajabon'), ('Elias Pi\xf1a', 'Elias Pi\xf1a'), ('San Jose de Ocoa', 'San Jose de Ocoa'), ('Santiago Rodriguez', 'Santiago Rodr\xedguez'), ('Independencia', 'Independencia'), ('Pedernales', 'Pedernales')], default='Ninguno', max_length=40),
        ),
        migrations.AlterField(
            model_name='loan',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='income_range',
            field=models.CharField(choices=[('0', 'RD$8,000 - 15,000'), ('1', 'RD$15,000 - 25,000'), ('2', 'RD$25,000 - 35,000'), ('3', 'RD$35,000 - 45,000'), ('4', 'RD$45,000 - 55,000'), ('5', 'RD$55,000 - 65,000'), ('6', 'RD$65,000 - 75,000'), ('7', 'RD$75,000 - 85,000'), ('8', 'RD$85,000 - 95,000'), ('9', 'RD$95,000 - 100,000'), ('10', 'RD$95,000 - 100,000'), ('11', 'RD$100,000 - 110,000'), ('12', 'RD$110,000 - +')], max_length=2),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_reason',
            field=models.CharField(choices=[('Prestamo personal', 'Prestamo personal'), ('Compra vehiculo', 'Compra vehiculo'), ('Compra casa', 'Compra casa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='work_time',
            field=models.CharField(choices=[('0', 'Menos de 1 a\xf1o'), ('1', '1 a\xf1o'), ('2', '2 a\xf1os'), ('3', '3 a\xf1os'), ('4', '4 a\xf1os'), ('5', '5 a\xf1os'), ('6', '6 a\xf1os'), ('7', '7 a\xf1os'), ('8', '8 a\xf1os'), ('9', '9 a\xf1os')], max_length=1),
        ),
    ]
