# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20171115_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='loan',
            name='birth_date',
            field=models.DateField(verbose_name='2017-11-15'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='other_income',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='province',
            field=models.CharField(blank=True, choices=[('Santo Domingo Este', 'Santo Domingo Este'), ('Distrito Nacional', 'Distrito Nacional'), ('Santiago', 'Santiago'), ('San Crist\xf3bal', 'San Crist\xf3bal'), ('La Vega', 'La Vega'), ('Puerto Plata', 'Puerto Plata'), ('San Pedro de Macor\xeds', 'San Pedro de Macor\xeds'), ('Duarte', 'Duarte'), ('La Altagracia', 'La Altagracia'), ('La Romana', 'La Romana'), ('San Juan', 'San Juan'), ('Espaillat', 'Espaillat'), ('Azua', 'Azua'), ('Barahona', 'Barahona'), ('Monte Plata', 'Monte Plata'), ('Peravia', 'Peravia'), ('Monsenor Nouel', 'Monse\xf1or Nouel'), ('Valverde', 'Valverde'), ('Sanchez Ramirez', 'S\xe1nchez Ram\xedrez'), ('Maria Trinidad Sanchez', 'Mar\xeda Trinidad S\xe1nchez'), ('Montecristi', 'Montecristi'), ('Samana', 'Saman\xe1'), ('Bahoruco', 'Bahoruco'), ('Hermanas Mirabal', 'Hermanas Mirabal'), ('El Seibo', 'El Seibo'), ('Hato Mayor', 'Hato Mayor'), ('Dajabon', 'Dajabon'), ('Elias Pi\xf1a', 'Elias Pi\xf1a'), ('San Jose de Ocoa', 'San Jose de Ocoa'), ('Santiago Rodriguez', 'Santiago Rodr\xedguez'), ('Independencia', 'Independencia'), ('Pedernales', 'Pedernales')], max_length=40),
        ),
    ]
