# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auto_20171115_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='birth_date',
            field=models.DateField(verbose_name='1980-09-15'),
        ),
    ]
