# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20171115_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='birth_date',
        ),
    ]
