# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_remove_loan_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_reason',
            field=models.CharField(choices=[('Prestamo personal', 'Prestamo personal'), ('Compra vehiculo', 'Compra vehiculo'), ('Compra casa', 'Compra casa'), ('Vacaciones', 'Vacaciones')], max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='work_time',
            field=models.CharField(choices=[('0', 'Menos de 1 a\xf1o'), ('1', '1 a\xf1o'), ('2', '2 a\xf1os'), ('3', '3 a\xf1os'), ('4', '4 a\xf1os'), ('5', '5 a\xf1os'), ('6', '6 a\xf1os'), ('7', '7 a\xf1os'), ('8', '8 a\xf1os'), ('9', '9 a\xf1os o m\xe1s')], max_length=1),
        ),
    ]
